version: '3.8'

services:
  pos:
    build: ./pos_service
    ports:
      - "8000:8000"
    networks:
      - fintech_net

  acquirer:
    build: ./acquirer_service
    ports:
      - "8001:8001"
    networks:
      - fintech_net

networks:
  fintech_net:
    driver: bridge