version: '3.8'

services:
  pos:
    build: ./pos_service
    ports:
      - "8000:8000"
    networks:
      - fintech_net

  acquirer:
    build: ./acquirer_service
    ports:
      - "8001:8001"
    networks:
      - fintech_net
  issuer:
    build:
      context: ./issuer_service
    container_name: issuer
    ports:
      - "8002:8002"
networks:
  fintech_net:
    driver: bridge